### PR TITLE
Package MNE-Python 1.0 snapshot

### LINKED ISSUE #50: Update to 1.0?
Any reason all builds are currently named 0.24? It seems like they should be 1.0.dev0 or so, since that's what they need to work with...?

### PR DESCRIPTION
**Pull request by hoechenberger**
Fixes #50

cc @larsoner

### CODE REVIEW

**Comment by hoechenberger** [comment]
@larsoner I'm not updating Python to 3.10 here, as apparently with the huge stack of software we're now including, dependency resolution fails if we use Python 3.10. Hopefully this will be resolved by the time we do the first 1.0-followup release.

**Comment by larsoner** [comment]
> I'm not updating Python to 3.10 here, as apparently with the huge stack of software we're now including, dependency resolution fails if we use Python 3.10. Hopefully this will be resolved by the time we do the first 1.0-followup release.

VTK has no 3.10 release, so we're probably stuck for a while. I think it's fine to be on 3.9 for now

**Comment by hoechenberger** [comment]
@larsoner There are 3.10 builds of VTK on conda-forge. It's none of our MNE dependencies holding us back here, it's one of the other packages we're including in the installer, I just haven't narrowed down which one. But like you said, sticking with 3.9 should be okay for now

**Comment by rob-luke** [comment]
> Would you know if the latest stable release of MNE-NIRS is compatible with MNE-Python 1.0

Not sure. I can check Thursday and release a new version if required (currently traveling).

**Comment by rob-luke** [comment]
> Would you know if the latest stable release of MNE-NIRS is compatible with MNE-Python 1.0

Ok, I am back at my desk and can look at MNE-NIRS now. The main branch of MNE-NIRS is compatible with MNE-Python main, it is not compatible with 0.24. The current released version of MNE-NIRS is compatible with MNE-Python 0.24.

I usually wait until MNE-Python cuts a release, then I update the dependency of MNE-Python in MNE-NIRS to match the latest release. In other words, I would usually wait for MNE-Python to release 1.0. Then I will change the requirements in MNE-NIRS to require `mne_python >= 1.0` and cut a new release.

Does this answer your question @hoechenberger

**Comment by hoechenberger** [comment]
Thanks @rob-luke, this helps!

**Comment by rob-luke** [comment]
Let me know if you want me to do anything different @hoechenberger

**Comment by hoechenberger** [comment]
Im really undecided how to go about this! Any chance you'd be able to join us in tomorrow's dev meeting?

**Comment by rob-luke** [comment]
The next meeting is in the 26th at 3am AEST?

**Comment by rob-luke** [comment]
Sorry, I won't make 3am (usually I can push myself, but 3am is rough :wink:).
If the release of MNE-Python is made on a week day, then I can ensure a new MNE-NIRS is released the following day (if that helps).

**Comment by hoechenberger** [comment]
I don't think there's reason to stress out, we'll just have to find a solution that works best for everyone :)

**Comment by hoechenberger** [comment]
> @larsoner I'm not updating Python to 3.10 here, as apparently with the huge stack of software we're now including, dependency resolution fails if we use Python 3.10. Hopefully this will be resolved by the time we do the first 1.0-followup release.

It seems that `dipy` is the culprit: it currently doesn't support Python 3.10.
https://github.com/conda-forge/dipy-feedstock/pull/37#issuecomment-1002335909

**Pull request merged**
